# Generated by Django 4.1.3 on 2022-11-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='sex',
            field=models.CharField(default='M', max_length=128),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='test',
            field=models.CharField(default='test', max_length=128),
        ),
    ]
