# Generated by Django 4.1.3 on 2022-11-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_subscribers_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='date',
            field=models.DateField(null=True, verbose_name='dd.mm.yyyy'),
        ),
    ]
